require("__base__.prototypes.entity.pipecovers")
local item_sounds = require("__base__.prototypes.item_sounds")
local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")

local function steam_inserter_pipe_straight()
	return {
		north = {
			filename = "__steam_inserter__/graphics/pipe-inserter-base-2-directions-vertical.png",
			priority = "extra-high",
			width = 128,
			height = 128,
			shift = util.by_pixel(0, 32),
			scale = 0.5,
		},
		west = {
			filename = "__steam_inserter__/graphics/pipe-inserter-base-2-directions-horizontal.png",
			priority = "extra-high",
			width = 128,
			height = 128,
			shift = util.by_pixel(32, 0),
			scale = 0.5,
		},
		south = util.empty_sprite(),
		east = util.empty_sprite(),
	}
end

local function steam_inserter_pipe_cross()
	return {
		north = {
			filename = "__steam_inserter__/graphics/pipe-inserter-base-4-directions.png",
			priority = "extra-high",
			width = 128,
			height = 128,
			shift = util.by_pixel(0, 32),
			scale = 0.5,
		},
		west = {
			filename = "__steam_inserter__/graphics/pipe-inserter-base-4-directions.png",
			priority = "extra-high",
			width = 128,
			height = 128,
			shift = util.by_pixel(32, 0),
			scale = 0.5,
		},
		south = util.empty_sprite(),
		east = util.empty_sprite(),
	}
end

data:extend({
	{
		type = "item",
		name = "steam-inserter-straight",
		icon = "__base__/graphics/icons/burner-inserter.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "inserter",
		color_hint = { text = "S" },
		order = "gd[steam-inserter-straight]",
		inventory_move_sound = item_sounds.inserter_inventory_move,
		pick_sound = item_sounds.inserter_inventory_pickup,
		drop_sound = item_sounds.inserter_inventory_move,
		place_result = "steam-inserter-straight",
		weight = 20 * kg,
		stack_size = 50,
	},
	{
		type = "corpse",
		name = "steam-inserter-straight-remnants",
		icon = "__base__/graphics/icons/burner-inserter.png",
		icon_size = 64,
		icon_mipmaps = 4,
		flags = { "placeable-neutral", "not-on-map" },
		subgroup = "inserter-remnants",
		order = "a-d-a",
		selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
		tile_width = 1,
		tile_height = 1,
		selectable_in_game = false,
		time_before_removed = 60 * 60 * 15,
		final_render_layer = "remnants",
		remove_on_tile_placement = false,
		animation = {
			width = 128,
			height = 128,
			direction_count = 4,
			stripes = {
				{
					filename = "__steam_inserter__/graphics/pipe-inserter-base-2-directions-horizontal-remnants.png",
					width_in_frames = 1,
					height_in_frames = 1,
				},
				{
					filename = "__steam_inserter__/graphics/pipe-inserter-base-2-directions-vertical-remnants.png",
					width_in_frames = 1,
					height_in_frames = 1,
				},
				{
					filename = "__steam_inserter__/graphics/pipe-inserter-base-2-directions-horizontal-remnants.png",
					width_in_frames = 1,
					height_in_frames = 1,
				},
				{
					filename = "__steam_inserter__/graphics/pipe-inserter-base-2-directions-vertical-remnants.png",
					width_in_frames = 1,
					height_in_frames = 1,
				},
			},
			scale = 0.5,
		},
	},
	{
		type = "inserter",
		name = "steam-inserter-straight",
		icon = "__base__/graphics/icons/burner-inserter.png",
		icon_size = 64,
		icon_mipmaps = 4,
		flags = { "placeable-neutral", "placeable-player", "player-creation" },
		minable = { mining_time = 0.1, result = "steam-inserter-straight" },
		max_health = 150,
		corpse = "steam-inserter-straight-remnants",
		dying_explosion = "inserter-explosion",
		resistances = {
			{ type = "fire", percent = 90 },
		},
		collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
		selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
		damaged_trigger_effect = hit_effects.entity(),
		pickup_position = { 0, -1 },
		insert_position = { 0, 1.2 },
		energy_per_movement = "7kJ",
		energy_per_rotation = "7kJ",
		energy_source = {
			type = "fluid",
			burns_fluid = true,
			scale_fluid_usage = true,
			fluid_box = {
				filter = "steam",
				pipe_picture = steam_inserter_pipe_straight(),
				pipe_covers = pipecoverspictures(),
				always_draw_covers = false,
				volume = 100,
				pipe_connections = {
					{ direction = defines.direction.east, position = { 0, 0 } },
					{ direction = defines.direction.west, position = { 0, 0 } },
				},
				production_type = "input-output",
			},
			smoke = {
				{
					name = "smoke",
					frequency = 3,
					position = { 0, 0 },
					starting_vertical_speed = 0.1,
					starting_frame_deviation = 60,
				},
			},
		},
		extension_speed = 0.1,
		rotation_speed = 0.06,
		filter_count = 5,
		icon_draw_specification = {
			-- this one is changed a bit. Because you constantly see fluid filter this settings make it easier
			shift = { 0, -0.3 },
			scale = 0.8,
			render_layer = "entity-info-icon-above",
			--scale = 0.5,
			--render_layer = "entity-info-icon",
		},
		fast_replaceable_group = "inserter",
		impact_category = "metal",
		open_sound = sounds.inserter_open,
		close_sound = sounds.inserter_close,
		working_sound = sounds.inserter_fast,
		hand_base_picture = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base.png",
			priority = "extra-high",
			width = 32,
			height = 136,
			scale = 0.25,
		},
		hand_closed_picture = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		hand_open_picture = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		hand_base_shadow = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
			priority = "extra-high",
			width = 32,
			height = 132,
			scale = 0.25,
		},
		hand_closed_shadow = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed-shadow.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		hand_open_shadow = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open-shadow.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		platform_picture = util.empty_sprite(),
		circuit_connector = circuit_connector_definitions["inserter"],
		circuit_wire_max_distance = inserter_circuit_wire_max_distance,
		default_stack_control_input_signal = inserter_default_stack_control_input_signal,
	},
	{
		type = "item",
		name = "steam-inserter-cross",
		icon = "__base__/graphics/icons/burner-inserter.png",
		icon_size = 64,
		icon_mipmaps = 4,
		subgroup = "inserter",
		color_hint = { text = "S+" },
		order = "gd[steam-inserter-cross]",
		inventory_move_sound = item_sounds.inserter_inventory_move,
		pick_sound = item_sounds.inserter_inventory_pickup,
		drop_sound = item_sounds.inserter_inventory_move,
		place_result = "steam-inserter-cross",
		weight = 20 * kg,
		stack_size = 50,
	},
	{
		type = "corpse",
		name = "steam-inserter-cross-remnants",
		icon = "__base__/graphics/icons/burner-inserter.png",
		icon_size = 64,
		icon_mipmaps = 4,
		flags = { "placeable-neutral", "not-on-map" },
		subgroup = "inserter-remnants",
		order = "a-d-b",
		selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
		tile_width = 1,
		tile_height = 1,
		selectable_in_game = false,
		time_before_removed = 60 * 60 * 15,
		final_render_layer = "remnants",
		remove_on_tile_placement = false,
		animation = {
			filename = "__steam_inserter__/graphics/pipe-inserter-base-4-directions-remnants.png",
			line_length = 1,
			width = 128,
			height = 128,
			frame_count = 1,
			direction_count = 1,
			scale = 0.5,
		},
	},
	{
		type = "inserter",
		name = "steam-inserter-cross",
		icon = "__base__/graphics/icons/burner-inserter.png",
		icon_size = 64,
		icon_mipmaps = 4,
		flags = { "placeable-neutral", "placeable-player", "player-creation" },
		minable = { mining_time = 0.1, result = "steam-inserter-cross" },
		max_health = 150,
		corpse = "steam-inserter-cross-remnants",
		dying_explosion = "inserter-explosion",
		resistances = {
			{ type = "fire", percent = 90 },
		},
		collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
		selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
		damaged_trigger_effect = hit_effects.entity(),
		pickup_position = { 0, -1 },
		insert_position = { 0, 1.2 },
		energy_per_movement = "7kJ",
		energy_per_rotation = "7kJ",
		energy_source = {
			type = "fluid",
			burns_fluid = true,
			scale_fluid_usage = true,
			fluid_box = {
				filter = "steam",
				pipe_picture = steam_inserter_pipe_cross(),
				pipe_covers = pipecoverspictures(),
				always_draw_covers = false,
				volume = 100,
				pipe_connections = {
					{ direction = defines.direction.north, position = { 0, 0 } },
					{ direction = defines.direction.south, position = { 0, 0 } },
					{ direction = defines.direction.east, position = { 0, 0 } },
					{ direction = defines.direction.west, position = { 0, 0 } },
				},
				production_type = "input-output",
			},
			smoke = {
				{
					name = "smoke",
					frequency = 3,
					position = { 0, 0 },
					starting_vertical_speed = 0.1,
					starting_frame_deviation = 60,
				},
			},
		},
		extension_speed = 0.1,
		rotation_speed = 0.06,
		filter_count = 5,
		icon_draw_specification = {
			-- this one is changed a bit. Because you constantly see fluid filter this settings make it easier
			shift = { 0, -0.3 },
			scale = 0.8,
			render_layer = "entity-info-icon-above",
			--scale = 0.5,
			--render_layer = "entity-info-icon",
		},
		fast_replaceable_group = "inserter",
		impact_category = "metal",
		open_sound = sounds.inserter_open,
		close_sound = sounds.inserter_close,
		working_sound = sounds.inserter_fast,
		hand_base_picture = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base.png",
			priority = "extra-high",
			width = 32,
			height = 136,
			scale = 0.25,
		},
		hand_closed_picture = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		hand_open_picture = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		hand_base_shadow = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
			priority = "extra-high",
			width = 32,
			height = 132,
			scale = 0.25,
		},
		hand_closed_shadow = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed-shadow.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		hand_open_shadow = {
			filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open-shadow.png",
			priority = "extra-high",
			width = 72,
			height = 164,
			scale = 0.25,
		},
		platform_picture = util.empty_sprite(),
		circuit_connector = circuit_connector_definitions["inserter"],
		circuit_wire_max_distance = inserter_circuit_wire_max_distance,
		default_stack_control_input_signal = inserter_default_stack_control_input_signal,
	},
})
